FROM jenkins/jenkins:lts

USER root

RUN apt-get update && \
    apt-get install -y docker.io docker-compose-plugin ansible git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER jenkins